# Generated by Django 5.1.1 on 2024-09-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="business_hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
                ("store_id", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="store",
            fields=[
                ("store_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "timezone_str",
                    models.CharField(default="America/Chicago", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="store_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.BigIntegerField()),
                ("timestamp_utc", models.DateTimeField()),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
