# Generated by Django 5.1.1 on 2024-09-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.BigIntegerField()),
                ("uptime_last_hour", models.IntegerField()),
                ("uptime_last_day", models.IntegerField()),
                ("uptime_last_week", models.IntegerField()),
                ("downtime_last_hour", models.IntegerField()),
                ("downtime_last_day", models.IntegerField()),
                ("downtime_last_week", models.IntegerField()),
            ],
        ),
    ]
